import "dotenv/config";

const {
  PORT,
  NODE_ENV,
  API_PREFIX,
  MONGODB_URL,
  DB_NAME,
  LOGS_DB_NAME,
  ALLOWED_ORIGINS,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  SUPER_ADMIN_EMAIL,
  SUPER_ADMIN_PASSWORD,
  SUPER_ADMIN_FIRST_NAME,
  SUPER_ADMIN_LAST_NAME,
} = process.env;

const portNumber = PORT || 4001;

export default {
  portNumber,
  NODE_ENV,
  API_PREFIX,
  MONGODB_URL,
  DB_NAME,
  LOGS_DB_NAME,
  ALLOWED_ORIGINS,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  SUPER_ADMIN_EMAIL,
  SUPER_ADMIN_PASSWORD,
  SUPER_ADMIN_FIRST_NAME,
  SUPER_ADMIN_LAST_NAME,
};
